---
title: "The Effect of Weapons on Global Terrorism in the 21st Century"
author: "Group 7 (Wendi Sapp, Elham Rastegari, Adel KabiriKopaei, Sepehr Pashoutani)"
date: "September 30, 2017"
output:
  pdf_document: default
  html_document: default
bibliography: GTDBProject.bib
toc: true
csl: nature.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Abstract

Continuous media coverage of terroristic attacks makes one consider his or her own personal safety and the safety of neighbors, friends, and family. As we continue to transition to a global society, governments work around the clock to protect the welfare of its citizens. Maintained by researchers at the National Consortium for the Study of Terrorism and Responses to Terrorism (SMART), the Global Terrorism Database contains details on more than 170,000 terrorist attacks since 1970. We investigate temporal trends in choice of weapon and regional concentration in terroristic violence. Selecting those contries which seem to have the highest rate of either receiving terror attacks or producing those who carry out attacks, we combine the terrorism data with world population and geographical data to obtain a standardized view of violence per capita and per country area $(km^2)$. However, historical data of populations and geographic boundaries are difficult to obtain, therefore, only recent trends will be examined for the aforementioned. We also study which countries suffer from terror attacks carried out by their fellow countrymen. We are also interested in investigating the correlation between several other factors and the number of terror attacks carried out by the people from different nationalities. These factors include literacy rate/education level, unemployment rate, and the percentage of people who believe that religion plays an important role in their daily life. An analysis such as this will allow peace-keepers to better distribute their efforts in reducing terrorist attacks and improve the safety of those in terror-ridden regions.

## I. Introduction

The complexity of global terroristic threats makes the subject an intriguing problem to study. There are many, well-documented correlations between terrorism and education [-@lafree_introducing_2007], poverty levels, regional economics,


## II. About the Data

In this section we would like to describe the data we are going to use for the analysis. For example we intend to study the trees data that comes with default R installation. There are 31 data points and 3 variables in this data set. The variables are Girth, Height, Volume. The data may not be tidy and we may have to prepare the data before our analysis can be done. We will discuss how we prepared the data


## III. Methodology

This section will include the methods you used for your analysis. You should include some
theoretical justification here. For example, why you think the method is applicable, what are the assumptions about the methods, whether your data satisfies those assumption or not etc.

## IV. Results

In result section you can start with an overview of what you have found during the exploration of data

## V. Conclusion

The conclusion is an elaboration of your abstract. Here you will discuss what you have done and how. The gist of the results need to be mentioned here. Please keep it in mind that there may be readers who only read your conclusion. So, make your conclusion complete so that no reader misses anything even if they don't want to read the whole document.

Each paragraph of the conclusion may discuss one result you have found or one concept you are proposing. Discuss your findings and why it is better and how it is compared to any existing methods may exist.

There should be one paragraph about the future direction of the work you have done.  You would like to make it so fascinating that the reader would wish to be involved in this work in future.

## References












