---
title: "GTDBProject Sandbox"
author: "Wendi Sapp"
date: "October 7, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## SandBox for EDA


Setting working directory and loading data into a dataframe.
```{r}
setwd("C:/Users/wendi/Google Drive/Courses/DataScience_Fall2017/GTDBproject/GTDBproject")

#GTdf <- read.csv("C:/Users/wendi/Google Drive/Courses/DataScience_Fall2017/GTDBproject/globalterrorismdb_0617dist.csv")

US_GTdf <- read.csv("C:/Users/wendi/Google Drive/Courses/DataScience_Fall2017/GTDBproject/GTDB_US_cont.csv")
```

Attempting EDA... where to begin... standard `summary()` and `plot()` will not work with 135 variables.

Let's start with some regional spatial data.
```{r fig1, out.width = '100%'}
library(maps)
library(ggplot2)

# subset the data to include only those which took place in the US
# US_GTdf <- subset(GTdf,country_txt=="United States")


# Remove those not in the continental US
US_GTdf <- subset(US_GTdf, provstate != "Alaska")
US_GTdf <- subset(US_GTdf, provstate != "Hawaii")


us.dat <- map_data("state")
ct.dat <- map_data("county")
ggplot(legend.position = "bottom") + geom_polygon(aes(long,lat, group=group), fill="grey65", data=ct.dat) + geom_polygon(aes(long,lat, group=group), color='white', fill=NA, data=us.dat) + theme_bw() + theme(axis.text = element_blank(), axis.title=element_blank(), legend.position = "bottom") + 
geom_point(size=2, alpha = 1/2, aes(longitude,latitude, color=weaptype1_txt), data=US_GTdf, legend.position = "bottom") 
  
```

