---
title: "Project"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R Markdown

This 

```{r}
library(data.table)
library(dplyr)
library(bit64)
library(ggplot2)
TerrorismData <- fread('C:/Users/erastegari/Desktop/Fall 2017/Data Science/project/gtd/globalterrorismdb_0617dist.csv')
#head(TerrorismData)
TerrorismData_DT <- data.table(TerrorismData)
length(TerrorismData_DT)
#filtering out those rows that there is doubt in being a terrorism attack
TerrorismData_DT_withoutDoubt <- TerrorismData_DT[TerrorismData_DT$doubtterr ==0]
# filtering out those rows that are associated with years 1970-1999
TerrorismData_DT_withoutDoubt_2000 <- TerrorismData_DT_withoutDoubt[TerrorismData_DT_withoutDoubt$iyear>1999]
# add one column with all values 1
TerrorismData_DT_withoutDoubt_2000$NumberofTerrorismAttacks <- rep(1, nrow(TerrorismData_DT_withoutDoubt_2000))
# grouping by year and weapon type
WeaponUseByYear <- TerrorismData_DT_withoutDoubt_2000[ , sum(NumberofTerrorismAttacks), by = list(iyear,weaptype1)]

WeaponType <- factor(WeaponUseByYear$weaptype1)
ggplot(Ready_for_plotting, aes(x= WeaponUseByYear$iyear, y= WeaponUseByYear$V1, color = WeaponType)) + geom_line() + xlab('Year') +ylab('Occurance')

```


